import { color } from './color'
import { common } from './common'
import { data } from './data'
import { element } from './element'
import { event } from './event'
import { file } from './file'
import { number } from './number'
import { platform } from './platform'
import { speech } from './speech'
import { string } from './string'

export * from './color'
export * from './common'
export * from './data'
export * from './element'
export * from './event'
export * from './file'
export * from './number'
export * from './platform'
export * from './speech'
export * from './string'

export default { number, data, element, event, common, color, file, string, platform, speech }
